lints.workspace = true

[package]
name = "gix-utils"
version = "0.1.14"
repository.workspace = true
license.workspace = true
description = "A crate with `gitoxide` utilities that don't need feature toggles"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = true

[features]
bstr = ["dep:bstr"]

[dependencies]
fastrand = "2.0.0"
bstr = { version = "1.5.0", default-features = false, features = ["std"], optional = true }
unicode-normalization = { version = "0.1.19", default-features = false }
