lints.workspace = true

[package]
name = "gix-tix"
version = "0.0.0"
repository.workspace = true
license.workspace = true
description = "A tool like `tig`, but minimal, fast and efficient"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
