lints.workspace = true

[package]
name = "gix-submodule"
version = "0.17.0"
repository.workspace = true
license.workspace = true
description = "A crate of the gitoxide project dealing git submodules"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
gix-pathspec = { version = "^0.9.0", path = "../gix-pathspec" }
gix-refspec = { version = "^0.28.0", path = "../gix-refspec" }
gix-config = { version = "^0.43.0", path = "../gix-config" }
gix-path = { version = "^0.10.14", path = "../gix-path" }
gix-url = { version = "^0.29.0", path = "../gix-url" }

bstr = { version = "1.5.0", default-features = false }
thiserror = "2.0.0"

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
gix-features = { path = "../gix-features", features = ["walkdir"] }
