lints.workspace = true

[package]
name = "gix-url"
version = "0.29.0"
repository.workspace = true
license.workspace = true
description = "A crate of the gitoxide project implementing parsing and serialization of gix-url"
authors.workspace = true
edition.workspace = true
include = ["src/**/*", "LICENSE-*", "tests/baseline/**/*"]
rust-version.workspace = true

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "bstr/serde"]

[dependencies]
gix-features = { version = "^0.40.0", path = "../gix-features" }
gix-path = { version = "^0.10.14", path = "../gix-path" }

serde = { version = "1.0.114", optional = true, default-features = false, features = ["std", "derive"] }
thiserror = "2.0.0"
url = "2.5.2"
bstr = { version = "1.3.0", default-features = false, features = ["std"] }
percent-encoding = "2.3.1"

document-features = { version = "0.2.0", optional = true }

[dev-dependencies]
assert_matches = "1.5.0"
gix-testtools = { path = "../tests/tools" }

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
