lints.workspace = true

[package]
name = "gix-tui"
version = "0.0.0"
repository.workspace = true
license.workspace = true
description = "A crate of the gitoxide project dedicated to a terminal user interface to interact with git repositories"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "gixi"
path = "src/main.rs"
doctest = false
test = false

[dependencies]
