lints.workspace = true

[package]
name = "gix-validate"
version = "0.9.3"
repository.workspace = true
license.workspace = true
description = "Validation functions for various kinds of names in git"
authors.workspace = true
edition.workspace = true
include = ["src/**/*", "LICENSE-*"]
rust-version.workspace = true

[lib]
doctest = false
test = true

[dependencies]
thiserror = "2.0.0"
bstr = { version = "1.3.0", default-features = false, features = ["std"] }

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
