lints.workspace = true

[package]
name = "gix-worktree-state"
version = "0.17.0"
repository.workspace = true
license.workspace = true
description = "A crate of the gitoxide project implementing setting the worktree to a particular state"
authors.workspace = true
edition.workspace = true
include = ["src/**/*", "LICENSE-*"]
rust-version.workspace = true
autotests = false

[lib]
doctest = false

[dependencies]
gix-worktree = { version = "^0.39.0", path = "../gix-worktree", default-features = false, features = ["attributes"] }
gix-index = { version = "^0.38.0", path = "../gix-index" }
gix-fs = { version = "^0.13.0", path = "../gix-fs" }
gix-hash = { version = "^0.16.0", path = "../gix-hash" }
gix-object = { version = "^0.47.0", path = "../gix-object" }
gix-glob = { version = "^0.18.0", path = "../gix-glob" }
gix-path = { version = "^0.10.14", path = "../gix-path" }
gix-features = { version = "^0.40.0", path = "../gix-features" }
gix-filter = { version = "^0.17.0", path = "../gix-filter" }

io-close = "0.3.7"
thiserror = "2.0.0"
bstr = { version = "1.3.0", default-features = false }

[target.'cfg(unix)'.dependencies]
rustix = { version = "0.38.20", default-features = false, features = [
    "std",
    "fs",
] }
